apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}
spec:
  selector:
   matchLabels:
    app: {{ .Release.Name }}-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.image }}
          imagePullPolicy: "IfNotPresent"
          env:
           - name: POSTGRES_USER
             valueFrom:
               secretKeyRef:
                 name: {{ .Values.secret_name }}
                 key: postgres-username
           - name: POSTGRES_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: {{ .Values.secret_name }}
                 key: postgres-password
           - name: POSTGRES_DB
             value: {{ .Values.db_name }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb

      resources:
        requests:
          cpu: {{ .Values.resources.requests.cpu }}
          memory: {{ .Values.resources.requests.memory }}
        limits:
          cpu: {{ .Values.resources.limits.cpu }}
          memory: {{ .Values.resources.limits.memory }}
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgres-pv-claim
