apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: {{ .Release.Name }}-postgres
spec:
  ports:
    - name: postgres
      port: 5432
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-postgres