name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Specify the branch that triggers the workflow

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Package Helm charts
      run: |
        rm -rf publish
        mkdir -p publish && cd publish
        for dir in $(ls -d ../*/); do
          if [ "$dir" == "../publish/" ]; then
            continue
          fi
          helm package $dir
        done
        helm repo index --url https://l4r-s.github.io/helm-charts .

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
